### ISSUE TITLE
Version 4.8.2 - 2019020100 class icon conflict with boost

### ISSUE THREAD

**Issue by ocimjr** [adpe/moodle-filter_fontawesome#5]
Hi,

At file filter.php line 99 on version for moodle 3.4 we see this 
`$embed = '<i class="icon fa '.$matches[1].' fa-fw" aria-hidden="true"></i>';`

But class icon causes a conflict with boost. See this image

![screen shot 2019-02-27 at 9 06 17 am](https://user-images.githubusercontent.com/37626833/53496733-a2960680-3a70-11e9-90db-381892555fde.png)

So fa-2x doesn't work, since property font-size is override by .icon.

Thanks

**Comment by adpe** [comment]
Hello @ocimjr 

Thanks for your report - you're right and I've opened this Tracker https://tracker.moodle.org/browse/MDL-63461. But the problem is not on Moodle side.

On the `master` and `MOODLE_35_STABLE` branch we've removed the not necessary .icon class. But it was forgotten in the `MOODLE_33_STABLE` branch. As you can see [here](https://github.com/adpe/moodle-filter_fontawesome/blob/master/CHANGES.md#removed) I've removed that.

I'll provide the fix soon and release a new version in the Moodle plugins repository.

**Comment by adpe** [comment]
I've just released the new version, check it out https://moodle.org/plugins/pluginversion.php?id=19079

**Comment by ocimjr** [comment]
Thank you !
